### ISSUE TITLE
List problems

### ISSUE THREAD

**Issue by NotWiggo** [Phumix/MyBB-GoMobile#3]
OL and UL elements appear to be ignored when calculating the space required for post_body resulting in the UL or OL text overlaying subsequent posts. See [img]http://notthelounge.com/images/gomob.PNG[/img]

**Comment by NotWiggo** [comment]
Fixed by adding

`.post_content ul {
   position: static;
}

.post_content ul > li {
   display: block;
   float: none;
}

.post_content ol {
   position: static;
}

.post_content ol > li {
   display: block;
   float: none;
}`

to global.css

**Comment by NotWiggo** [comment]
user agent stylesheet still overrides "list-style-type: disc" for <UL> and "list-style-type: decimal" is set for <OL> by user agent stylesheet but numbers do not display.

**Comment by NotWiggo** [comment]
user agent stylesheet still overrides "list-style-type: disc" for `<UL>` and "list-style-type: decimal" is set for `<OL>` by user agent stylesheet but numbers do not display.

**Comment by NotWiggo** [comment]
OK, all fixed with this code in global.css:

.post_content ul {
    list-style-type: disc;
    list-style-position: inside;
    position: static;
}

.post_content ul > li {
   display: list-item;
   float: none;
}

.post_content ol {
   position: static;
}

.post_content ol > li {
   display: list-item;
   float: none;
}

**Comment by Phumix** [comment]
Solved in latest update.
